/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/attributes/java335.xml
 */
const Attributes = {

	GENERIC.MAXHEALTH: {name: "max_health", min: 0, max: 1024, default: 20},

	GENERIC.ABSORPTION: {name: "absorption", min: 0, max: 4, default: 0},

	GENERIC.MOVEMENTSPEED: {name: "movement_speed", min: 0, max: 24791, default: 0.1},

	GENERIC.KNOCKBACKRESISTANCE: {name: "knockback_resistance", min: 0, max: 1, default: 0},

	GENERIC.ATTACKDAMAGE: {name: "attack_damage", min: 0, max: 2048, default: 2},

	GENERIC.ATTACKSPEED: {name: "attack_speed", min: 0, max: 1024, default: 4},

}