/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/attributes/pocket113.xml
 */
const Attributes = {

	MINECRAFT:HEALTH: {name: "health", min: 0, max: 20, default: 20},

	MINECRAFT:GENERIC.ABSORPTION: {name: "absorption", min: 0, max: 4, default: 0},

	MINECRAFT:PLAYER.HUNGER: {name: "hunger", min: 0, max: 20, default: 20},

	MINECRAFT:PLAYER.SATURATION: {name: "saturation", min: 0, max: 20, default: 5},

	MINECRAFT:PLAYER.EXPERIENCE: {name: "experience", min: 0, max: 1, default: 0},

	MINECRAFT:PLAYER.LEVEL: {name: "level", min: 0, max: 24791, default: 0},

	MINECRAFT:MOVEMENT: {name: "speed", min: 0, max: 24791, default: 0.1},

	MINECRAFT:GENERIC.KNOCKBACK_RESISTANCE: {name: "knockback_resistance", min: 0, max: 1, default: 0},

}